app_default:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_products:
    path:     /Products
    defaults: { _controller: AppBundle:Product:index }

app_categories:
    path:     /Categories
    defaults: { _controller: AppBundle:Category:index }


app_product_create:
    path:     /Product/Create
    defaults: { _controller: AppBundle:Product:Create }
    
app_product_change:
    path:     /Product/Change/{id}
    defaults: { _controller: AppBundle:Product:Change }
    requirements:
        id: '\d+'

app_product_delete:
    path:     /Product/Delete/{id}
    defaults: { _controller: AppBundle:Product:Delete }
    requirements:
        id: '\d+'


app_category_create:
    path:     /Category/Create
    defaults: { _controller: AppBundle:Category:Create }

app_category_change:
    path:     /Category/Change/{id}
    defaults: { _controller: AppBundle:Category:Change }
    requirements:
        id: '\d+'

app_category_delete:
    path:     /Category/Delete/{id}
    defaults: { _controller: AppBundle:Category:Delete }
    requirements:
        id: '\d+'