app_user_index:
    path:     /users
    defaults: { _controller: AppBundle:User:index }

app_user_profile:
    path:     /userprofile/{id}
    defaults: { _controller: AppBundle:User:userprofile }

app_user_select:
    path:     /userselect/{property}/{value}
    defaults: { _controller: AppBundle:User:userselect }

app_user_create:
    path:     /usercreate
    defaults: { _controller: AppBundle:User:usercreate }

app_user_edit:
    path:     /useredit
    defaults: { _controller: AppBundle:User:edit }

app_user_delete:
    path:     /userdelete
    defaults: { _controller: AppBundle:User:delete }
